---
abstract: 'Online payment processing via CashCow'
author:
  - 'Jonas B. Nielsen, (jonasbn) <jonasbn@cpan.org>'
build_requires:
  Test::Kwalitee: 0
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.131560'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-CashCow
provides:
  Business::OnlinePayment::CashCow:
    file: lib/Business/OnlinePayment/CashCow.pm
    version: 0.10
requires:
  Business::OnlinePayment: 0.02
  Data::Dumper: 0
  Exporter: 0
  Net::SSLeay: 0
  URI::Escape: 0
  XML::Simple: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Business-OnlinePayment-CashCow
  homepage: http://logicLAB.jira.com/browse/BOPCC
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: http://logicLAB.jira.com/svn/BOPCC
version: 0.10
