---
name: Business-OnlinePayment-CashCow
version: 0.07
author:
  - 'Jonas B. Nielsen, (jonasbn) - C<< <jonasbn@cpan.org> >>'
abstract: Online payment processing via CashCow
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Business::OnlinePayment: 0.02
  Data::Dumper: 0
  Exporter: 0
  Net::SSLeay: 0
  XML::Simple: 0
provides:
  Business::OnlinePayment::CashCow:
    file: lib/Business/OnlinePayment/CashCow.pm
    version: 0.07
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
